<?php
/**
 * Handles adding and inserting MarketPress short codes from within the tinymce editor
 *
 * @since 1.0
 * @package MarketPress
 */
add_action( 'wp_ajax_mp_shortcode_builder_search_products', array( 'MP_Shortcode_Builder', 'search_products' ) );

class MP_Shortcode_Builder {

	/**
	 * Refers to a single instance of the class.
	 *
	 * @since 1.0
	 * @access private
	 * @var object
	 */
	private static $_instance = null;

	/**
	 * Refers to the product categories
	 *
	 * @since 1.0
	 * @access public
	 * @var array
	 */
	protected $_product_cats = array();

	/**
	 * Refers to the product tags
	 *
	 * @since 1.0
	 * @access public
	 * @var array
	 */
	protected $_product_tags = array();

	/**
	 * Gets the single instance of the class.
	 *
	 * @since 1.0
	 * @access public
	 * @return object
	 */
	public static function get_instance() {
		if ( is_null( self::$_instance ) ) {
			self::$_instance = new MP_Shortcode_Builder();
		}
		return self::$_instance;
	}

	/**
	 * Searches posts
	 *
	 * @since 1.0
	 * @access public
	 * @action wp_ajax_mp_shortcode_builder_search_posts
	 */
	public static function search_products() {
		add_filter( 'posts_search', array( __CLASS__, 'search_by_title_only' ), 500, 2 );

		$page = max( 1, absint( isset( $_GET['page'] ) ? $_GET['page'] : 1 ) );
		$per_page = absint( isset( $_GET['per_page'] ) ? $_GET['per_page'] : 20 );
		if ( $per_page < 10 ) {
			$per_page = 10;
		} elseif ( $per_page > 100 ) {
			$per_page = 100;
		}
		$search_term = isset( $_GET['search_term'] ) ? sanitize_text_field( wp_unslash( $_GET['search_term'] ) ) : '';

		$query	 = new WP_Query( array(
			'paged'					 => $page,
			'posts_per_page'		 => $per_page,
			's'						 => $search_term,
			'update_post_meta_cache' => false,
			'update_post_term_cache' => false,
			'no_found_rows'			 => false,
			'orderby'				 => 'title',
			'order'					 => 'ASC',
			'post_type'				 => MP_Product::get_post_type(),
		) );
		$data	 = array( 'posts' => array(), 'posts_per_page' => $per_page, 'total' => $query->found_posts );

		while ( $query->have_posts() ) : $query->the_post();
			$data[ 'posts' ][] = array( 'id' => get_the_ID(), 'text' => get_the_title() );
		endwhile;

		wp_send_json( $data );
	}

	/**
	 * Search by title only
	 *
	 * @since 1.0
	 * @access public
	 * @filter posts_search
	 * @param string $search
	 * @param object $wp_query
	 * @return string
	 */
	public static function search_by_title_only( $search, &$wp_query ) {
		global $wpdb;

		if ( empty( $search ) ) {
			return $search; // skip processing - no search term in query
		}

		$q			 = $wp_query->query_vars;
		$n			 = !empty( $q[ 'exact' ] ) ? '' : '%';
		$search		 = '';
		$searchand	 = '';

		foreach ( (array) $q[ 'search_terms' ] as $term ) {
			$term		 = esc_sql( $wpdb->esc_like( $term ) );
			$search .= "{$searchand}($wpdb->posts.post_title LIKE '{$n}{$term}{$n}')";
			$searchand	 = ' AND ';
		}

		if ( !empty( $search ) ) {
			$search = " AND ({$search}) ";
			if ( !is_user_logged_in() ) {
				$search .= " AND ($wpdb->posts.post_password = '') ";
			}
		}

		return $search;
	}

	/**
	 * Constructor.
	 *
	 * @since 1.0
	 * @access private
	 */
	private function __construct() {
		$this->_product_cats = get_terms( 'product_category', 'hide_empty=0' );
		$this->_product_tags = get_terms( 'product_tag', 'hide_empty=0' );

		add_action( 'media_buttons', array( &$this, 'media_buttons' ) );
		add_action( 'admin_enqueue_scripts', array( &$this, 'enqueue_styles_scripts' ) );
		add_action( 'in_admin_footer', array( &$this, 'display_short_code_form' ) );
		add_filter( 'wp_dropdown_cats', array( &$this, 'wp_dropdown_cats' ), 10, 2 );
	}

	/**
	 * Add data-default attribute to html generated by wp_dropdown_categories() function
	 *
	 * @since 1.0
	 * @access public
	 * @filter wp_dropdown_cats
	 * @return string
	 */
	public function wp_dropdown_cats( $html, $args ) {
		return str_replace( '<select ', '<select data-default="-1" ', $html );
	}

	/**
	 * Displays the short code form
	 *
	 * @since 1.0
	 * @access public
	 */
	public function display_short_code_form() {
		// Shortcodes initialisieren
			   $shortcodes = array(
			'mp_list_categories' => __( 'Zeigt eine Liste der Produktkategorien an.', 'mp' ),
			'mp_list_products'   => __( 'Zeigt eine Liste oder ein Raster von Produkten an.', 'mp' ),
			'mp_product'         => __( 'Zeigt ein einzelnes Produkt an.', 'mp' ),
			'mp_cart'            => __( 'Zeigt den Warenkorb an.', 'mp' ),
			'mp_checkout'        => __( 'Zeigt das Checkout-Formular an.', 'mp' ),
			'mp_order_status'    => __( 'Zeigt den Bestellstatus an.', 'mp' ),
		);
			   if ( did_action( 'media_buttons' ) == 0 ) {
			// Only continue if a tinymce editor exists on the current page
			return;
		}
		
		if ( ! function_exists( 'is_plugin_active_for_network' ) ) {
			require_once( ABSPATH . '/wp-admin/includes/plugin.php' );
		}
		
			   // Einstellungen laden, damit $settings für Multisite-Shortcodes verfügbar ist
			   $settings = get_option( 'mp_settings' );

			   if ( ! function_exists( 'mp_get_plugin_slug' ) ) {
			   function mp_get_plugin_slug() {
				   if ( file_exists( dirname( __FILE__ ) . '/includes/admin/dash-notice/psource-dash-notification.php' ) ) {
					   return 'marketpress/marketpress.php';
				   } else {
					   return 'wordpress-ecommerce/marketpress.php';
				   }
			   }
			if ( ( isset($settings['main_blog']) && mp_is_main_site() ) || isset($settings['main_blog']) && !$settings['main_blog'] ) {
				$mu_shortcodes = array(
					'mp_list_global_products'	  => __( 'Zeigt eine Liste oder ein Raster deiner globalen Produkte an.', 'mp' ),
					'mp_global_categories_list'   => __( 'Zeigt eine Liste deiner globalen Kategorien an.', 'mp' ),
					'mp_global_tag_cloud'		  => __( 'Zeigt eine Wolke oder Liste deiner globalen Produkt-Tags an.', 'mp' ),
				);
				
				$shortcodes = array_merge($shortcodes, $mu_shortcodes);
			}
		}
		
		?>
		<div id="mp-shortcode-builder" style="display:none">
			<form id="mp-shortcode-builder-form">
				<h3><?php _e( 'E-Commerce-Shortcode hinzufuegen', 'mp' ); ?></h3>
				<strong><?php _e( 'Was moechtest du tun?', 'mp' ); ?></strong><br />
				<select name="shortcode">
					<option value=""><?php _e( 'Aktion auswaehlen', 'mp' ); ?></option>
					<?php foreach ( $shortcodes as $shortcode => $label ) : ?>
						<option value="<?php echo esc_attr( $shortcode ); ?>"><?php echo '[' . $shortcode . '] ' . $label; ?></option>
					<?php endforeach; ?>
				</select>

				<div class="shortcode-attributes">
					<h2><?php _e( 'Attribute', 'mp' ); ?></h2>
					<?php
					foreach ( $shortcodes as $shortcode => $label ) {
						$func = 'display_' . $shortcode . '_attributes';

						if ( method_exists( $this, $func ) ) {
							call_user_func( array( &$this, $func ) );
						}
					}
					?>
				</div>
				<?php $this->display_shortcode_builder_form_buttons(); ?>
			</form>
		</div>
		<?php
	}

	/**
	 * Displays the [mp_list_categories] short code attributes
	 *
	 * @since 1.0
	 * @access public
	 */
	public function display_mp_list_categories_attributes() {
		?>
		<table id="mp-list-categories-shortcode" class="form-table" style="display:none">
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Wenn ein Wert gesetzt ist, wird ein Link zu allen Kategorien angezeigt, falls der Stil auf Liste steht.', 'mp' ); ?></span></span> show_option_all</th>
				<td>
					<input type="text" name="show_option_all" data-default="" value="" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Sortiert Kategorien alphabetisch, nach eindeutiger Kategorie-ID oder nach der Anzahl der Beitraege in der Kategorie.', 'mp' ); ?></span></span> orderby</th>
				<td>
					<select name="orderby" data-default="name">
						<?php foreach ( array( 'ID', 'name', 'slug', 'count', 'term_group' ) as $value ) : ?>
							<option <?php selected( $value, 'name' ); ?>><?php echo $value; ?></option>
						<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Sortierreihenfolge fuer Kategorien (aufsteigend oder absteigend).', 'mp' ); ?></span></span> order</th>
				<td>
					<select name="order" data-default="ASC">
						<?php foreach ( array( 'ASC', 'DESC' ) as $value ) : ?>
							<option <?php selected( $value, 'ASC' ); ?>><?php echo $value; ?></option>
						<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Darstellungsstil der Kategorienliste. Mit Liste werden Kategorien als Listenelemente angezeigt, mit Keine ohne besonderes Format (Listenelemente sind durch <br>-Tags getrennt).', 'mp' ); ?></span></span> style</th>
				<td>
					<select name="style" data-default="list">
						<?php foreach ( array( 'list', 'none' ) as $value ) : ?>
							<option <?php selected( $value, 'list' ); ?>><?php echo $value; ?></option>
						<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Schaltet die Anzeige der aktuellen Beitragsanzahl je Kategorie ein oder aus.', 'mp' ); ?></span></span> show_count</th>
				<td>
					<input type="checkbox" name="show_count" data-default="" value="1" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Schaltet die Anzeige von Kategorien ohne Beitraege ein oder aus.', 'mp' ); ?></span></span> hide_empty</th>
				<td>
					<input type="checkbox" name="hide_empty" data-default="1" value="1" checked />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Legt fest, ob die Beschreibung einer Kategorie in das title-Attribut der erzeugten Links eingefuegt wird (z. B. &lt;a title="&lt;em&gt;Kategoriebeschreibung&lt;/em&gt;" href="...).', 'mp' ); ?></span></span> use_desc_for_title</th>
				<td>
					<input type="checkbox" name="use_desc_for_title" data-default="1" value="1" checked />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Zeigt nur Kategorien an, die Unterkategorien der mit diesem Parameter angegebenen Kategorie sind.', 'mp' ); ?></span></span>  child_of</th>
				<td>
					<?php
					wp_dropdown_categories( array(
						'taxonomy'			 => 'product_category',
						'hide_empty'		 => 0,
						'show_option_none'	 => __( 'Beliebig', 'mp' ),
						'name'				 => 'child_of',
					) );
					?>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Zeigt einen Link zum RSS-2-Feed jeder Kategorie an und legt den Linktext fest. Standard ist kein Text und keine Feed-Anzeige.', 'mp' ); ?></span></span> feed</th>
				<td>
					<input type="text" name="feed" data-default="" value="" />
				</td>
			</tr>
			<tr>
				<th scope="row">feed_type</th>
				<td>
					<input type="text" name="feed_type" data-default="" value="" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Setzt eine URI fuer ein Bild (meist ein RSS-Icon), das als Link zum RSS-2-Feed jeder Kategorie dient. Dieser Parameter ueberschreibt den feed-Parameter. Es gibt keinen Standardwert.', 'mp' ); ?></span></span> feed_image</th>
				<td>
					<input type="text" name="feed_image" data-default="" value="" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Schliesst eine oder mehrere Kategorien aus den Ergebnissen aus. Der Parameter include muss leer sein.', 'mp' ); ?></span></span> exclude</th>
				<td>
					<select name="exclude" class="mp-chosen-select" data-placeholder="<?php _e( 'Kategorien auswaehlen', 'mp' ); ?>" multiple>
						<?php
						foreach ( $this->_product_cats as $cat ) {
							if ( isset( $cat ) ) {
								?>
								<option value="<?php echo esc_attr( isset( $cat->term_id ) ? $cat->term_id : ''  ); ?>"><?php echo isset( $cat->name ) ? $cat->name : ''; ?></option>
								<?php
							}
						}
						?>
					</select>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Nur diese Kategorien einschliessen.', 'mp' ); ?></span></span> include</th>
				<td>
					<select name="include" class="mp-chosen-select" data-placeholder="<?php _e( 'Kategorien auswaehlen', 'mp' ); ?>" multiple>
						<?php
						foreach ( $this->_product_cats as $cat ) :
							if ( isset( $cat ) ) {
								?>
								<option value="<?php echo esc_attr( isset( $cat->term_id ) ? $cat->term_id : ''  ); ?>"><?php echo isset( $cat->name ) ? $cat->name : ''; ?></option>
							<?php }endforeach;
						?>
					</select>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Schliesst den Kategoriebaum aus den Ergebnissen aus. Der Parameter include muss leer sein. Wenn hierarchical aktiv ist, verwende exclude statt exclude_tree.', 'mp' ); ?></span></span> exclude_tree</th>
				<td>
					<select name="exclude_tree" class="mp-chosen-select" data-placeholder="<?php _e( 'Kategorien auswaehlen', 'mp' ); ?>" multiple>
						<?php foreach ( $this->_product_cats as $cat ) : ?>
							<option value="<?php echo esc_attr( isset( $cat->term_id ) ? $cat->term_id : ''  ); ?>"><?php echo isset( $cat->name ) ? $cat->name : ''; ?></option>
						<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Zeigt Unterkategorien als innere Listenelemente (unter dem Elternelement) oder inline an.', 'mp' ); ?></span></span> hierarchical</th>
				<td>
					<input type="checkbox" name="hierarchical" data-default="1" value="1" checked />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Legt Titel und Stil des aeusseren Listenelements fest. Wenn vorhanden, aber leer, wird das aeussere Listenelement nicht angezeigt.', 'mp' ); ?></span></span> title_li</th>
				<td>
					<input type="text" name="title_li" data-default="Categories" value="Categories" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Legt den Text fest, der angezeigt wird, wenn keine Kategorien gelistet sind.', 'mp' ); ?></span></span> show_option_none</th>
				<td>
					<input type="text" name="show_option_none" data-default="Keine Kategorien" value="Keine Kategorien" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Legt die Anzahl der anzuzeigenden Kategorien fest. Dadurch wird der SQL-LIMIT-Wert gesetzt.', 'mp' ); ?></span></span> number</th>
				<td>
					<input type="text" name="number" data-default="" value="" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Dieser Parameter steuert, wie viele Ebenen der Kategorienhierarchie in der Kategorienliste enthalten sind. HINWEIS: Das Argument "hierarchical" ist standardmaessig deaktiviert und ueberschreibt depth, ausser es ist true. Bei false werden alle Kategorien angezeigt. Bei true wird der Wert aus "depth" verwendet.', 'mp' ); ?></span></span> depth</th>
				<td>
					<input type="text" name="depth" data-default="0" value="0" />
					<ul>
						<li><code>0</code> - <?php _e( 'Alle Kategorien und Unterkategorien (Standard).', 'mp' ); ?></li>
						<li><code>-1</code> - <?php _e( 'Alle Kategorien in flacher Form (ohne Einrueckung) anzeigen (ueberschreibt hierarchical).', 'mp' ); ?></li>
						<li><code>1</code> - <?php _e( 'Nur Kategorien der obersten Ebene anzeigen.', 'mp' ); ?></li>
						<li><code>n</code> - <?php _e( 'Der Wert n (eine Zahl) gibt die Tiefe (Ebene) an, bis zu der Kategorien angezeigt werden.', 'mp' ); ?></li>
					</ul>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Berechnet Link- oder Beitragsanzahlen unter Einbeziehung von Elementen aus Unterkategorien. Wenn show_counts und hierarchical true sind, wird dies automatisch auf true gesetzt.', 'mp' ); ?></span></span> pad_counts</th>
				<td>
					<input type="checkbox" name="pad_counts" data-default="0" value="1" />
				</td>
			</tr>
		</table>
		<?php
	}

	/**
	 * Displays the [mp_dropdown_categories] short code attributes
	 *
	 * @since 1.0
	 * @access public
	 */
	public function display_mp_dropdown_categories_attributes() {
		?>
		<table id="mp-dropdown-categories-shortcode" class="form-table" style="display:none">
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Wenn ein Wert gesetzt ist, wird ein Link zu allen Kategorien angezeigt, falls der Stil auf Liste steht.', 'mp' ); ?></span></span> show_option_all</th>
				<td>
					<input type="text" name="show_option_all" data-default="" value="" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Sortiert Kategorien alphabetisch, nach eindeutiger Kategorie-ID oder nach der Anzahl der Beitraege in der Kategorie.', 'mp' ); ?></span></span> orderby</th>
				<td>
					<select name="orderby" data-default="name">
						<?php foreach ( array( 'ID', 'name', 'slug', 'count', 'term_group' ) as $value ) : ?>
							<option <?php selected( $value, 'name' ); ?>><?php echo $value; ?></option>
						<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Sortierreihenfolge fuer Kategorien (aufsteigend oder absteigend).', 'mp' ); ?></span></span> order</th>
				<td>
					<select name="order" data-default="ASC">
						<?php foreach ( array( 'ASC', 'DESC' ) as $value ) : ?>
							<option <?php selected( $value, 'ASC' ); ?>><?php echo $value; ?></option>
						<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<!--<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php /*_e( 'Darstellungsstil der Kategorienliste. Mit Liste werden Kategorien als Listenelemente angezeigt, mit Keine ohne besonderes Format (Listenelemente sind durch <br>-Tags getrennt).', 'mp' ); */?></span></span> style</th>
				<td>
					<select name="style" data-default="list">
						<?php /*foreach ( array( 'list', 'none' ) as $value ) : */?>
							<option <?php /*selected( $value, 'list' ); */?>><?php /*echo $value; */?></option>
						<?php /*endforeach; */?>
					</select>
				</td>
			</tr>-->
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Schaltet die Anzeige der aktuellen Beitragsanzahl je Kategorie ein oder aus.', 'mp' ); ?></span></span> show_count</th>
				<td>
					<input type="checkbox" name="show_count" data-default="" value="1" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Schaltet die Anzeige von Kategorien ohne Beitraege ein oder aus.', 'mp' ); ?></span></span> hide_empty</th>
				<td>
					<input type="checkbox" name="hide_empty" data-default="1" value="1" checked />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Zeigt nur Kategorien an, die Unterkategorien der mit diesem Parameter angegebenen Kategorie sind.', 'mp' ); ?></span></span>  child_of</th>
				<td>
					<?php
					wp_dropdown_categories( array(
						'taxonomy'			 => 'product_category',
						'hide_empty'		 => 0,
						'show_option_none'	 => __( 'Beliebig', 'mp' ),
						'name'				 => 'child_of',
					) );
					?>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Schliesst eine oder mehrere Kategorien aus den Ergebnissen aus. Der Parameter include muss leer sein.', 'mp' ); ?></span></span> exclude</th>
				<td>
					<select name="exclude" class="mp-chosen-select" data-placeholder="<?php _e( 'Kategorien auswaehlen', 'mp' ); ?>" multiple>
						<?php
						$cats = get_categories( array(
							'hide_empty' => 0,
							'taxonomy'	 => 'product_category'
						) );

						foreach ( $cats as $cat ) :
							?>
							<option value="<?php echo esc_attr( $cat->term_id ); ?>"><?php echo $cat->name; ?></option>
						<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Schliesst den Kategoriebaum aus den Ergebnissen aus. Der Parameter include muss leer sein. Wenn hierarchical aktiv ist, verwende exclude statt exclude_tree.', 'mp' ); ?></span></span> exclude_tree</th>
				<td>
					<select name="exclude_tree" class="mp-chosen-select" data-placeholder="<?php _e( 'Kategorien auswaehlen', 'mp' ); ?>" multiple>
						<?php
						$cats = get_categories( array(
							'hide_empty' => 0,
							'taxonomy'	 => 'product_category'
						) );

						foreach ( $cats as $cat ) :
							?>
							<option value="<?php echo esc_attr( $cat->term_id ); ?>"><?php echo $cat->name; ?></option>
						<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Zeigt Unterkategorien als innere Listenelemente (unter dem Elternelement) oder inline an.', 'mp' ); ?></span></span> hierarchical</th>
				<td>
					<input type="checkbox" name="hierarchical" data-default="1" value="1" checked />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Legt den Text fest, der angezeigt wird, wenn keine Kategorien gelistet sind.', 'mp' ); ?></span></span> show_option_none</th>
				<td>
					<input type="text" name="show_option_none" data-default="<?php echo esc_attr( __( 'Keine Kategorien', 'mp' ) ); ?>" value="<?php echo esc_attr( __( 'Keine Kategorien', 'mp' ) ); ?>" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Die maximale Tiefe. Wird ignoriert, sofern hierarchical nicht auf true steht.', 'mp' ); ?></span></span> depth</th>
				<td>
					<input type="text" name="depth" data-default="0" value="0" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Berechnet Link- oder Beitragsanzahlen unter Einbeziehung von Elementen aus Unterkategorien. Wenn show_counts und hierarchical true sind, wird dies automatisch auf true gesetzt.', 'mp' ); ?></span></span> pad_counts</th>
				<td>
					<input type="checkbox" name="pad_counts" data-default="0" value="1" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Welche Kategorie-ID ausgewaehlt ist.', 'mp' ); ?></span></span> selected</th>
				<td>
					<input type="text" name="selected" data-default="" value="" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Wert des "id"-Attributs fuer das Select-Element. ', 'mp' ); ?></span></span> id</th>
				<td>
					<input type="text" name="id" data-default="0" value="0" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Wert des "name"-Attributs fuer das Select-Element. ', 'mp' ); ?></span></span> name</th>
				<td>
					<input type="text" name="name" data-default="cat" value="cat" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Wert des "tabindex"-Attributs fuer das Select-Element. ', 'mp' ); ?></span></span> tab_index</th>
				<td>
					<input type="text" name="tab_index" data-default="0" value="0" />
				</td>
			</tr>
		</table>
		<?php
	}

	/**
	 * Displays the [mp_tag_cloud] short code attributes
	 *
	 * @since 1.0
	 * @access public
	 */
	public function display_mp_tag_cloud_attributes() {
		?>
		<table id="mp-tag-cloud-shortcode" class="form-table" style="display:none">
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Die Textgroesse des Tags mit dem kleinsten Zaehlwert (Einheit wird durch den Parameter unit bestimmt).', 'mp' ); ?></span></span> smallest</th>
				<td>
					<input type="text" name="smallest" data-default="8" value="8" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Die Textgroesse des Tags mit dem groessten Zaehlwert (Einheit wird durch den Parameter unit bestimmt).', 'mp' ); ?></span></span> largest</th>
				<td>
					<input type="text" name="largest" data-default="22" value="22" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Masseinheit fuer den kleinsten und groessten Wert. Kann jeder CSS-Laengenwert sein, z. B. pt, px, em, %.', 'mp' ); ?></span></span> unit</th>
				<td>
					<input type="text" name="unit" data-default="pt" value="pt" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Die Anzahl der Tags, die in der Wolke angezeigt werden sollen. (Mit "0" werden alle Tags angezeigt.)', 'mp' ); ?></span></span> number</th>
				<td>
					<input type="text" name="number" data-default="45" value="45" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Format der Tag-Wolken-Anzeige.', 'mp' ); ?></span></span> format</th>
				<td>
					<label for="mp-tag-cloud-format-flat"><input type="radio" name="format" id="mp-tag-cloud-format-flat" data-default="flat" value="flat" checked /> <?php _e( 'Durch Leerzeichen getrennt, wie im Parameter "separator" definiert.', 'mp' ); ?></label><br />
					<label for="mp-tag-cloud-format-list"><input type="radio" name="format" id="mp-tag-cloud-format-list" data-default="flat" value="list" /> <?php _e( 'UL mit der Klasse "wp-tag-cloud"', 'mp' ); ?></label>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Der Text/Abstand zwischen Tags)', 'mp' ); ?></span></span> separator</th>
				<td>
					<input type="text" name="separator" data-default="\n" value="\n" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Sortierung der Tags.', 'mp' ); ?></span></span> orderby</th>
				<td>
					<label for="mp-tag-cloud-orderby-name"><input type="radio" name="orderby" id="mp-tag-cloud-orderby-name" data-default="name" value="name" checked /> <?php _e( 'Name', 'mp' ); ?></label><br />
					<label for="mp-tag-cloud-orderby-count"><input type="radio" name="orderby" id="mp-tag-cloud-orderby-count" data-default="count" value="count" /> <?php _e( 'Anzahl', 'mp' ); ?></label>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Sortierreihenfolge.', 'mp' ); ?></span></span> order</th>
				<td>
					<label for="mp-tag-cloud-order-asc"><input type="radio" name="order" id="mp-tag-cloud-order-asc" data-default="ASC" value="ASC" checked /> <?php _e( 'Aufsteigend', 'mp' ); ?></label><br />
					<label for="mp-tag-cloud-order-desc"><input type="radio" name="order" id="mp-tag-cloud-order-desc" data-default="ASC" value="DESC" /> <?php _e( 'Absteigend', 'mp' ); ?></label><br />
					<label for="mp-tag-cloud-order-rand"><input type="radio" name="order" id="mp-tag-cloud-order-rand" data-default="RAND" value="RAND" /> <?php _e( 'Zufaellig', 'mp' ); ?></label>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Kommagetrennte Liste von Tags (term_id), die ausgeschlossen werden sollen. Beispiel: exclude=5,27 bedeutet, dass Tags mit term_id 5 oder 27 NICHT angezeigt werden. Standard ist kein Ausschluss.', 'mp' ); ?></span></span> exclude</th>
				<td>
					<input type="text" name="exclude" data-default="" value="" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Kommagetrennte Liste von Tags (term_id), die eingeschlossen werden sollen. Beispiel: include=5,27 bedeutet, dass nur Tags mit term_id 5 oder 27 angezeigt werden. Standard ist alles einschliessen.', 'mp' ); ?></span></span> include</th>
				<td>
					<input type="text" name="include" data-default="" value="" />
				</td>
			</tr>
		</table>
		<?php
	}

	/**
	 * Displays the [mp_featured_products] short code attributes
	 *
	 * @since 1.0
	 * @access public
	 */
	public function display_mp_featured_products_attributes() {
		?>
		<table id="mp-featured-products-shortcode" class="form-table" style="display:none">
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Ob die Produktliste paginiert werden soll. Nuetzlich, um nur einen Teil anzuzeigen.', 'mp' ); ?></span></span> paginate</th>
				<td>
					<input type="checkbox" name="paginate" data-default="<?php echo esc_attr( mp_get_setting( 'paginate' ) ); ?>" value="1" <?php checked( 1, mp_get_setting( 'paginate' ) ); ?> />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Die Seitenzahl, die in der Produktliste angezeigt wird, wenn "paginate" auf true steht.', 'mp' ); ?></span></span> page</th>
				<td>
					<input type="text" name="page" data-default="1" value="1" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Wie viele Produkte in der Produktliste angezeigt werden, wenn "paginate" auf true steht.', 'mp' ); ?></span></span> per_page</th>
				<td>
					<input type="text" name="per_page" data-default="<?php echo esc_attr( mp_get_setting( 'per_page' ) ); ?>" value="<?php echo esc_attr( mp_get_setting( 'per_page' ) ); ?>" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Nach welchem Feld Produkte sortiert werden.', 'mp' ); ?></span></span> order_by</th>
				<td>
					<select name="order_by" data-default="<?php echo esc_attr( mp_get_setting( 'order_by' ) ); ?>">
						<?php
						$data = array(
							'title'	 => __( 'Produktname', 'mp' ),
							'date'	 => __( 'Veroeffentlichungsdatum', 'mp' ),
							'ID'	 => __( 'Produkt-ID', 'mp' ),
							'author' => __( 'Produktautor', 'mp' ),
							'sales'	 => __( 'Anzahl der Verkaeufe', 'mp' ),
							'price'	 => __( 'Produktpreis', 'mp' ),
							'rand'	 => __( 'Zufaellig', 'mp' ),
						);

						foreach ( $data as $value => $label ) :
							?>
							<option value="<?php echo esc_attr( $value ); ?>" <?php selected( $value, mp_get_setting( 'order_by' ) ); ?>><?php echo $label; ?></option>
						<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Sortierrichtung fuer Produkte.', 'mp' ); ?></span></span> order</th>
				<td>
					<label><input type="radio" name="order" data-default="<?php echo esc_attr( mp_get_setting( 'order' ) ); ?>" value="ASC" <?php checked( 'ASC', mp_get_setting( 'order' ) ); ?> /> <?php _e( 'Aufsteigend', 'mp' ); ?></label> &nbsp; &nbsp;
					<label><input type="radio" name="order" data-default="<?php echo esc_attr( mp_get_setting( 'order' ) ); ?>" value="DESC" <?php checked( 'DESC', mp_get_setting( 'order' ) ); ?> /> <?php _e( 'Absteigend', 'mp' ); ?></label>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Begrenzt die Liste auf eine bestimmte Produktkategorie.', 'mp' ); ?></span></span> category</th>
				<td>
					<select name="category" data-default="" class="mp-chosen-select">
						<option value=""><?php _e( 'Keine', 'mp' ); ?></option>
						<?php foreach ( $this->_product_cats as $term ) : ?>
							<option value="<?php echo esc_attr( isset( $term->slug ) ? $term->slug : ''  ); ?>"><?php echo isset( $term->name ) ? $term->name : ''; ?></option>
						<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Begrenzt die Liste auf ein bestimmtes Produkt-Tag.', 'mp' ); ?></span></span> tag</th>
				<td>
					<select name="tag" data-default="" class="mp-chosen-select">
						<option value=""><?php _e( 'Keine', 'mp' ); ?></option>
						<?php foreach ( $this->_product_tags as $term ) : ?>
							<option value="<?php echo esc_attr( isset( $term->slug ) ? $term->slug : ''  ); ?>"><?php echo isset( $term->name ) ? $term->name : ''; ?></option>
						<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Produkte werden als Liste oder Raster angezeigt.', 'mp' ); ?></span></span> list_view</th>
				<td>
					<select name="list_view" data-default="" class="mp-chosen-select">
						<option value="1" <?php echo esc_attr( ( mp_get_setting( 'list_view' ) == '1' ) ? 'selected="selected"' : ''  ); ?>><?php _e( 'Liste', 'mp' ); ?></option>
						<option value="0" <?php echo esc_attr( ( mp_get_setting( 'list_view' ) == '0' ) ? 'selected="selected"' : ''  ); ?>><?php _e( 'Raster', 'mp' ); ?></option>
					</select>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Ob Produktfilter angezeigt werden sollen.', 'mp' ); ?></span></span> filters</th>
				<td>
					<label><input type="radio" name="filters" data-default="<?php echo esc_attr( mp_get_setting( 'show_filters' ) ); ?>" value="1" <?php checked( '1', mp_get_setting( 'show_filters' ) ); ?> /> <?php _e( 'Anzeigen', 'mp' ); ?></label> &nbsp; &nbsp;
					<label><input type="radio" name="filters" data-default="<?php echo esc_attr( mp_get_setting( 'show_filters' ) ); ?>" value="0" <?php checked( '1', mp_get_setting( 'show_filters' ) ); ?> /> <?php _e( 'Ausblenden', 'mp' ); ?></label>
				</td>
			</tr>
		</table>
		<?php
	}


	/**
	 * Displays the [mp_popular_products] short code attributes
	 *
	 * @since 1.0
	 * @access public
	 */
	public function display_mp_popular_products_attributes() {
		?>
		<table id="mp-popular-products-shortcode" class="form-table" style="display:none">
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Die maximale Anzahl anzuzeigender Produkte', 'mp' ); ?></span></span> number</th>
				<td>
					<input type="text" name="number" data-default="5" value="5" />
				</td>
			</tr>
		</table>	
		<?php
	}

	/**
	 * Displays the [mp_related_products] short code attributes
	 *
	 * @since 1.0
	 * @access public
	 */
	public function display_mp_related_products_attributes() {
		?>
		<table id="mp-related-products-shortcode" class="form-table" style="display:none">
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Das Produkt, fuer das aehnliche Elemente angezeigt werden sollen.', 'mp' ); ?></span></span> product_id</th>
				<td>
					<input type="text" class="mp-select-product" name="product_id" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Wie Produkte miteinander verknuepft werden', 'mp' ); ?></span></span> relate_by</th>
				<td>
					<select name="relate_by" data-default="<?php echo esc_attr( mp_get_setting( 'related_products->relate_by' ) ); ?>">
						<?php
						$data = array(
							'both'		 => __( 'Kategorie &amp; Tags', 'mp' ),
							'category'	 => __( 'Kategorie', 'mp' ),
							'tags'		 => __( 'Tags', 'mp' ),
						);

						foreach ( $data as $value => $label ) :
							?>
							<option value="<?php echo esc_attr( $value ); ?>" <?php selected( $value, mp_get_setting( 'related_products->relate_by' ) ); ?>><?php echo $label; ?></option>
						<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Wie viele aehnliche Elemente angezeigt werden sollen.', 'mp' ); ?></span></span> limit</th>
				<td>
					<input type="text" name="limit" data-default="<?php echo esc_attr( mp_get_setting( 'related_products->show_limit' ) ); ?>" value="<?php echo esc_attr( mp_get_setting( 'related_products->show_limit' ) ); ?>" />
				</td>
			</tr>
			<!--<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php /*_e( 'Whether to display the items as a simple list or based on the list/grid view setting.', 'mp' ); */?></span></span> simple_list</th>
				<td>
					<input type="checkbox" name="simple_list" data-default="<?php /*echo esc_attr( mp_get_setting( 'related_products->simple_list' ) ); */?>" <?php /*checked( 1, mp_get_setting( 'related_products->simple_list' ) ); */?> />
				</td>
			</tr>-->
		</table>	
		<?php
	}

	/**
	 * Displays the [mp_list_products] short code attributes
	 *
	 * @since 1.0
	 * @access public
	 */
	public function display_mp_list_products_attributes() {
		?>
		<table id="mp-list-products-shortcode" class="form-table" style="display:none">
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Ob die Produktliste paginiert werden soll. Nuetzlich, um nur einen Teil anzuzeigen.', 'mp' ); ?></span></span> paginate</th>
				<td>
					<input type="checkbox" name="paginate" data-default="<?php echo esc_attr( mp_get_setting( 'paginate' ) ); ?>" value="1" <?php checked( 1, mp_get_setting( 'paginate' ) ); ?> />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Die Seitenzahl, die in der Produktliste angezeigt wird, wenn "paginate" auf true steht.', 'mp' ); ?></span></span> page</th>
				<td>
					<input type="text" name="page" data-default="1" value="1" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Wie viele Produkte in der Produktliste angezeigt werden, wenn "paginate" auf true steht.', 'mp' ); ?></span></span> per_page</th>
				<td>
					<input type="text" name="per_page" data-default="<?php echo esc_attr( mp_get_setting( 'per_page' ) ); ?>" value="<?php echo esc_attr( mp_get_setting( 'per_page' ) ); ?>" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Nach welchem Feld Produkte sortiert werden.', 'mp' ); ?></span></span> order_by</th>
				<td>
					<select name="order_by" data-default="<?php echo esc_attr( mp_get_setting( 'order_by' ) ); ?>">
						<?php
						$data = array(
							'title'	 => __( 'Produktname', 'mp' ),
							'date'	 => __( 'Veroeffentlichungsdatum', 'mp' ),
							'ID'	 => __( 'Produkt-ID', 'mp' ),
							'author' => __( 'Produktautor', 'mp' ),
							'sales'	 => __( 'Anzahl der Verkaeufe', 'mp' ),
							'price'	 => __( 'Produktpreis', 'mp' ),
							'rand'	 => __( 'Zufaellig', 'mp' ),
						);

						foreach ( $data as $value => $label ) :
							?>
							<option value="<?php echo esc_attr( $value ); ?>" <?php selected( $value, mp_get_setting( 'order_by' ) ); ?>><?php echo $label; ?></option>
						<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Sortierrichtung fuer Produkte.', 'mp' ); ?></span></span> order</th>
				<td>
					<label><input type="radio" name="order" data-default="<?php echo esc_attr( mp_get_setting( 'order' ) ); ?>" value="ASC" <?php checked( 'ASC', mp_get_setting( 'order' ) ); ?> /> <?php _e( 'Aufsteigend', 'mp' ); ?></label> &nbsp; &nbsp;
					<label><input type="radio" name="order" data-default="<?php echo esc_attr( mp_get_setting( 'order' ) ); ?>" value="DESC" <?php checked( 'DESC', mp_get_setting( 'order' ) ); ?> /> <?php _e( 'Absteigend', 'mp' ); ?></label>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Begrenzt die Liste auf eine bestimmte Produktkategorie.', 'mp' ); ?></span></span> category</th>
				<td>
					<select name="category" data-default="" class="mp-chosen-select">
						<option value=""><?php _e( 'Keine', 'mp' ); ?></option>
						<?php foreach ( $this->_product_cats as $term ) : ?>
							<option value="<?php echo esc_attr( isset( $term->slug ) ? $term->slug : ''  ); ?>"><?php echo isset( $term->name ) ? $term->name : ''; ?></option>
						<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Begrenzt die Liste auf ein bestimmtes Produkt-Tag.', 'mp' ); ?></span></span> tag</th>
				<td>
					<select name="tag" data-default="" class="mp-chosen-select">
						<option value=""><?php _e( 'Keine', 'mp' ); ?></option>
						<?php foreach ( $this->_product_tags as $term ) : ?>
							<option value="<?php echo esc_attr( isset( $term->slug ) ? $term->slug : ''  ); ?>"><?php echo isset( $term->name ) ? $term->name : ''; ?></option>
						<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Produkte werden als Liste oder Raster angezeigt.', 'mp' ); ?></span></span> list_view</th>
				<td>
					<select name="list_view" data-default="" class="mp-chosen-select">
						<option value="1" <?php echo esc_attr( ( mp_get_setting( 'list_view' ) == '1' ) ? 'selected="selected"' : ''  ); ?>><?php _e( 'Liste', 'mp' ); ?></option>
						<option value="0" <?php echo esc_attr( ( mp_get_setting( 'list_view' ) == '0' ) ? 'selected="selected"' : ''  ); ?>><?php _e( 'Raster', 'mp' ); ?></option>
					</select>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Ob Produktfilter angezeigt werden sollen.', 'mp' ); ?></span></span> filters</th>
				<td>
					<label><input type="radio" name="filters" data-default="<?php echo esc_attr( mp_get_setting( 'show_filters' ) ); ?>" value="1" <?php checked( '1', mp_get_setting( 'show_filters' ) ); ?> /> <?php _e( 'Anzeigen', 'mp' ); ?></label> &nbsp; &nbsp;
					<label><input type="radio" name="filters" data-default="<?php echo esc_attr( mp_get_setting( 'show_filters' ) ); ?>" value="0" <?php checked( '1', mp_get_setting( 'show_filters' ) ); ?> /> <?php _e( 'Ausblenden', 'mp' ); ?></label>
				</td>
			</tr>
		</table>
		<?php
	}

	/**
	 * Displays the [mp_product] short code attributes
	 *
	 * @since 1.0
	 * @access public
	 */
	public function display_mp_product_attributes() {
		?>
		<table id="mp-product-shortcode" class="form-table" style="display:none">
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Die ID des anzuzeigenden Produkts.', 'mp' ); ?></span></span> product_id</th>
				<td>
					<input type="text" name="product_id" data-default="" class="mp-select-product" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Ob der Produkttitel angezeigt werden soll.', 'mp' ); ?></span></span> title</th>
				<td>
					<input type="checkbox" name="title" data-default="0" value="1" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Ob und welche Art von Inhalt angezeigt werden soll.', 'mp' ); ?></span></span> content</th>
				<td>
					<select name="content" data-default="full">
						<option value="0"><?php _e( 'Keine', 'mp' ); ?></option>
						<option value="excerpt"><?php _e( 'Auszug', 'mp' ); ?></option>
						<option value="full" selected><?php _e( 'Volltext', 'mp' ); ?></option>
					</select>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Ob und in welchem Kontext die Bildgroesse angezeigt werden soll.', 'mp' ); ?></span></span> image</th>
				<td>
					<select name="image" data-default="single">
						<option value="0"><?php _e( 'Keine', 'mp' ); ?></option>
						<option value="single" selected><?php _e( 'Einzeln', 'mp' ); ?></option>
						<option value="list"><?php _e( 'Liste', 'mp' ); ?></option>
					</select>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Ob Produkt-Metadaten (z. B. Preis, Kaufen-Button) angezeigt werden sollen.', 'mp' ); ?></span></span> meta</th>
				<td>
					<input type="checkbox" name="meta" data-default="0" value="1" />
				</td>
			</tr>
		</table>
		<?php
	}

	/**
	 * Displays the [mp_product_image] short code attributes
	 *
	 * @since 1.0
	 * @access public
	 */
	public function display_mp_product_image_attributes() {
		?>
		<table id="mp-product-image-shortcode" class="form-table" style="display:none">
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Die ID des Produkts.', 'mp' ); ?></span></span> product_id</th>
				<td>
					<input type="text" name="product_id" data-default="" class="mp-select-product" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Welcher Kontext fuer vordefinierte Groessenoptionen gilt.', 'mp' ); ?></span></span> context</th>
				<td>
					<select name="context" data-default="single">
						<option value="single" selected><?php _e( 'Einzeln', 'mp' ); ?></option>
						<option value="list"><?php _e( 'Liste', 'mp' ); ?></option>
						<option value="widget"><?php _e( 'Widget', 'mp' ); ?></option>
					</select>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Setzt eine benutzerdefinierte Pixelbreite/-hoehe. Wenn leer, gilt die durch "context" definierte Groesse.', 'mp' ); ?></span></span> size</th>
				<td>
					<input type="text" name="size" data-default="" value="" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Legt die Ausrichtung des Bildes fest.', 'mp' ); ?></span></span> align</th>
				<td>
					<label><input type="radio" name="align" data-default="<?php echo esc_attr( mp_get_setting( 'image_alignment_single' ) ); ?>" value="alignnone" <?php checked( 'alignnone', mp_get_setting( 'image_alignment_single' ) ); ?> /> <?php _e( 'Keine', 'mp' ); ?></label> &nbsp; &nbsp;
					<label><input type="radio" name="align" data-default="<?php echo esc_attr( mp_get_setting( 'image_alignment_single' ) ); ?>" value="alignleft" <?php checked( 'alignleft', mp_get_setting( 'image_alignment_single' ) ); ?> /> <?php _e( 'Links', 'mp' ); ?></label> &nbsp; &nbsp;
					<label><input type="radio" name="align" data-default="<?php echo esc_attr( mp_get_setting( 'image_alignment_single' ) ); ?>" value="alignright" <?php checked( 'alignright', mp_get_setting( 'image_alignment_single' ) ); ?> /> <?php _e( 'Rechts', 'mp' ); ?></label> &nbsp; &nbsp;
					<label><input type="radio" name="align" data-default="<?php echo esc_attr( mp_get_setting( 'image_alignment_single' ) ); ?>" value="aligncenter" <?php checked( 'aligncenter', mp_get_setting( 'image_alignment_single' ) ); ?> /> <?php _e( 'Zentriert', 'mp' ); ?></label> &nbsp; &nbsp;
				</td>
			</tr>
		</table>
		<?php
	}

	/**
	 * Displays the [mp_buy_button] short code attributes
	 *
	 * @since 1.0
	 * @access public
	 */
	public function display_mp_buy_button_attributes() {
		?>
		<table id="mp-buy-button-shortcode" class="form-table" style="display:none">
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Die ID des Produkts.', 'mp' ); ?></span></span> product_id</th>
				<td>
					<input type="text" name="product_id" data-default="" class="mp-select-product" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Welcher Kontext fuer die Anzeige gilt.', 'mp' ); ?></span></span> context</th>
				<td>
					<label><input type="radio" value="single" name="context" data-default="single" value="single" checked> <?php _e( 'Einzeln', 'mp' ); ?></label> &nbsp; &nbsp;
					<label><input type="radio" value="list" name="context" data-default="single" value="list"> <?php _e( 'Liste', 'mp' ); ?></label>
				</td>
			</tr>
		</table>
		<?php
	}

	/**
	 * Displays the [mp_product_price] short code attributes
	 *
	 * @since 1.0
	 * @access public
	 */
	public function display_mp_product_price_attributes() {
		?>
		<table id="mp-product-price-shortcode" class="form-table" style="display:none">
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Die ID des Produkts.', 'mp' ); ?></span></span> product_id</th>
				<td>
					<input type="text" name="product_id" data-default="" class="mp-select-product" />
				</td>
			</tr>
			<!--<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'A label to prepend to the price.', 'mp' ); ?></span></span> label</th>
				<td>
					<input type="text" name="label" data-default="Price:" value="Price:" />
				</td>
			</tr>-->
		</table>
		<?php
	}

	/**
	 * Displays the [mp_product_sku] short code attributes
	 *
	 * @since 1.0
	 * @access public
	 */
	public function display_mp_product_sku_attributes() {
		?>
		<table id="mp-product-sku-shortcode" class="form-table" style="display:none">
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Die ID des Produkts.', 'mp' ); ?></span></span> product_id</th>
				<td>
					<input type="text" name="product_id" data-default="" class="mp-select-product" />
				</td>
			</tr>		
		</table>
		<?php
	}
	
	/**
	 * Displays the [mp_product_stock] short code attributes
	 *
	 * @since 1.0
	 * @access public
	 */
	public function display_mp_product_stock_attributes() {
		?>
		<table id="mp-product-stock-shortcode" class="form-table" style="display:none">
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Die ID des Produkts.', 'mp' ); ?></span></span> product_id</th>
				<td>
					<input type="text" name="product_id" data-default="" class="mp-select-product" />
				</td>
			</tr>		
		</table>
		<?php
	}

	/**
	 * Displays the [mp_product_meta] short code attributes
	 *
	 * @since 1.0
	 * @access public
	 */
	public function display_mp_product_meta_attributes() {
		?>
		<table id="mp-product-meta-shortcode" class="form-table" style="display:none">
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Die ID des Produkts.', 'mp' ); ?></span></span> product_id</th>
				<td>
					<input type="text" name="product_id" data-default="" class="mp-select-product" />
				</td>
			</tr>
			<!--<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'A label to prepend to the price.', 'mp' ); ?></span></span> label</th>
				<td>
					<input type="text" name="label" data-default="Price:" value="Price:" />
				</td>
			</tr>-->
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Welcher Kontext fuer die Anzeige gilt.', 'mp' ); ?></span></span> context</th>
				<td>
					<label><input type="radio" value="single" name="context" data-default="single" value="single" checked> <?php _e( 'Einzeln', 'mp' ); ?></label> &nbsp; &nbsp;
					<label><input type="radio" value="list" name="context" data-default="single" value="list"> <?php _e( 'Liste', 'mp' ); ?></label>
				</td>
			</tr>			
		</table>
		<?php
	}

	/**
	 * Displays the [mp_cart_widget] short code attributes
	 *
	 * @since 1.0
	 * @access public
	 */
	public function display_mp_cart_widget_attributes() {
		?>
		<table id="mp-cart-widget-shortcode" class="form-table" style="display:none">
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Der Titel des Warenkorbs.', 'mp' ); ?></span></span> title</th>
				<td>
					<input type="text" name="title" data-default="" value="" />
				</td>
			</tr>			
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Der Text, der vor dem Warenkorb angezeigt wird.', 'mp' ); ?></span></span> custom_text</th>
				<td>
					<input type="text" name="custom_text" data-default="" value="" />
				</td>
			</tr>			
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Ob das Produktbild angezeigt oder ausgeblendet wird.', 'mp' ); ?></span></span> show_product_image</th>
				<td>
					<input type="checkbox" name="show_product_image" data-default="1" value="1" checked />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Ob die Produktmenge angezeigt oder ausgeblendet wird.', 'mp' ); ?></span></span> show_product_qty</th>
				<td>
					<input type="checkbox" name="show_product_qty" data-default="1" value="1" checked />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Ob der Produktpreis angezeigt oder ausgeblendet wird.', 'mp' ); ?></span></span> show_product_price</th>
				<td>
					<input type="checkbox" name="show_product_price" value="1" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Ob der Warenkorb nur auf Shop-Seiten angezeigt werden soll.', 'mp' ); ?></span></span> only_store_pages</th>
				<td>
					<input type="checkbox" name="only_store_pages" value="1" />
				</td>
			</tr>
		</table>
		<?php
	}

	/**
	 * Displays the [mp_cart_link] short code attributes
	 *
	 * @since 1.0
	 * @access public
	 */
	public function display_mp_cart_link_attributes() {
		?>
		<table id="mp-cart-link-shortcode" class="form-table" style="display:none">
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Ob ein klickbarer Link oder eine URL zurueckgegeben werden soll.', 'mp' ); ?></span></span> url</th>
				<td>
					<input type="checkbox" name="url" data-default="1" value="1" checked />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Der Text, der im Link angezeigt wird.', 'mp' ); ?></span></span> link_text</th>
				<td>
					<input type="text" name="link_text" data-default="" value="" />
				</td>
			</tr>			
		</table>
		<?php
	}

	/**
	 * Displays the [mp_store_link] short code attributes
	 *
	 * @since 1.0
	 * @access public
	 */
	public function display_mp_store_link_attributes() {
		?>
		<table id="mp-store-link-shortcode" class="form-table" style="display:none">
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Ob ein klickbarer Link oder eine URL zurueckgegeben werden soll.', 'mp' ); ?></span></span> url</th>
				<td>
					<input type="checkbox" name="url" data-default="1" value="1" checked />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Der Text, der im Link angezeigt wird.', 'mp' ); ?></span></span> link_text</th>
				<td>
					<input type="text" name="link_text" data-default="" value="" />
				</td>
			</tr>			
		</table>
		<?php
	}

	/**
	 * Displays the [mp_products_link] short code attributes
	 *
	 * @since 1.0
	 * @access public
	 */
	public function display_mp_products_link_attributes() {
		?>
		<table id="mp-products-link-shortcode" class="form-table" style="display:none">
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Ob ein klickbarer Link oder eine URL zurueckgegeben werden soll.', 'mp' ); ?></span></span> url</th>
				<td>
					<input type="checkbox" name="url" data-default="1" value="1" checked />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Der Text, der im Link angezeigt wird.', 'mp' ); ?></span></span> link_text</th>
				<td>
					<input type="text" name="link_text" data-default="" value="" />
				</td>
			</tr>			
		</table>
		<?php
	}
	
	/**
	 * Displays the [mp_list_global_products] short code attributes
	 *
	 * @since 1.0
	 * @access public
	 */
	public function display_mp_list_global_products_attributes() {
		?>
		<table id="mp-list-global-products-shortcode" class="form-table" style="display:none">
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Ob die Produktliste paginiert werden soll. Nuetzlich, um nur einen Teil anzuzeigen.', 'mp' ); ?></span></span> paginate</th>
				<td>
					<input type="checkbox" name="paginate" data-default="<?php echo esc_attr( mp_get_setting( 'paginate' ) ); ?>" value="1" <?php checked( 1, mp_get_setting( 'paginate' ) ); ?> />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Die Seitenzahl, die in der Produktliste angezeigt wird, wenn "paginate" auf true steht.', 'mp' ); ?></span></span> page</th>
				<td>
					<input type="text" name="page" data-default="1" value="1" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Wie viele Produkte in der Produktliste angezeigt werden, wenn "paginate" auf true steht.', 'mp' ); ?></span></span> per_page</th>
				<td>
					<input type="text" name="per_page" data-default="<?php echo esc_attr( mp_get_setting( 'per_page' ) ); ?>" value="<?php echo esc_attr( mp_get_setting( 'per_page' ) ); ?>" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Wie viele Produkte in der Produktliste angezeigt werden, wenn "paginate" auf false steht.', 'mp' ); ?></span></span> limit</th>
				<td>
					<input type="text" name="limit" data-default="<?php echo esc_attr( mp_get_setting( 'limit' ) ); ?>" value="<?php echo esc_attr( mp_get_setting( 'limit' ) ); ?>" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Nach welchem Feld Produkte sortiert werden.', 'mp' ); ?></span></span> order_by</th>
				<td>
					<select name="order_by" data-default="<?php echo esc_attr( mp_get_setting( 'order_by' ) ); ?>">
						<?php
						$data = array(
							'title'	 => __( 'Produktname', 'mp' ),
							'date'	 => __( 'Veroeffentlichungsdatum', 'mp' ),
							'ID'	 => __( 'Produkt-ID', 'mp' ),
							'author' => __( 'Produktautor', 'mp' ),
							'sales'	 => __( 'Anzahl der Verkaeufe', 'mp' ),
							'price'	 => __( 'Produktpreis', 'mp' ),
							'rand'	 => __( 'Zufaellig', 'mp' ),
						);

						foreach ( $data as $value => $label ) :
							?>
							<option value="<?php echo esc_attr( $value ); ?>" <?php selected( $value, mp_get_setting( 'order_by' ) ); ?>><?php echo $label; ?></option>
						<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Sortierrichtung fuer Produkte.', 'mp' ); ?></span></span> order</th>
				<td>
					<label><input type="radio" name="order" data-default="<?php echo esc_attr( mp_get_setting( 'order' ) ); ?>" value="ASC" <?php checked( 'ASC', mp_get_setting( 'order' ) ); ?> /> <?php _e( 'Aufsteigend', 'mp' ); ?></label> &nbsp; &nbsp;
					<label><input type="radio" name="order" data-default="<?php echo esc_attr( mp_get_setting( 'order' ) ); ?>" value="DESC" <?php checked( 'DESC', mp_get_setting( 'order' ) ); ?> /> <?php _e( 'Absteigend', 'mp' ); ?></label>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Begrenzt die Liste auf eine bestimmte Produktkategorie.', 'mp' ); ?></span></span> category</th>
				<td>
					<select name="category" data-default="" class="mp-chosen-select">
						<option value=""><?php _e( 'Keine', 'mp' ); ?></option>
						<?php foreach ( $this->_product_cats as $term ) : ?>
							<option value="<?php echo esc_attr( isset( $term->slug ) ? $term->slug : ''  ); ?>"><?php echo isset( $term->name ) ? $term->name : ''; ?></option>
						<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Begrenzt die Liste auf ein bestimmtes Produkt-Tag.', 'mp' ); ?></span></span> tag</th>
				<td>
					<select name="tag" data-default="" class="mp-chosen-select">
						<option value=""><?php _e( 'Keine', 'mp' ); ?></option>
						<?php foreach ( $this->_product_tags as $term ) : ?>
							<option value="<?php echo esc_attr( isset( $term->slug ) ? $term->slug : ''  ); ?>"><?php echo isset( $term->name ) ? $term->name : ''; ?></option>
						<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Produkte werden als Liste oder Raster angezeigt.', 'mp' ); ?></span></span> list_view</th>
				<td>
					<select name="list_view" data-default="" class="mp-chosen-select">
						<option value="1" <?php echo esc_attr( ( mp_get_setting( 'list_view' ) == '1' ) ? 'selected="selected"' : ''  ); ?>><?php _e( 'Liste', 'mp' ); ?></option>
						<option value="0" <?php echo esc_attr( ( mp_get_setting( 'list_view' ) == '0' ) ? 'selected="selected"' : ''  ); ?>><?php _e( 'Raster', 'mp' ); ?></option>
					</select>
				</td>
			</tr>
		</table>
		<?php
	}
	
	/**
	 * Displays the [mp_global_categories_list] short code attributes
	 *
	 * @since 1.0
	 * @access public
	 */
	public function display_mp_global_categories_list_attributes() {
		?>
		<table id="mp-global-categories-list-shortcode" class="form-table" style="display:none">
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Sortiert Kategorien alphabetisch, nach eindeutiger Kategorie-ID oder nach der Anzahl der Beitraege in der Kategorie.', 'mp' ); ?></span></span> orderby</th>
				<td>
					<select name="orderby" data-default="name">
						<?php foreach ( array( 'ID', 'name', 'slug', 'count', 'term_group' ) as $value ) : ?>
							<option <?php selected( $value, 'name' ); ?>><?php echo $value; ?></option>
						<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Sortierreihenfolge fuer Kategorien (aufsteigend oder absteigend).', 'mp' ); ?></span></span> order</th>
				<td>
					<select name="order" data-default="ASC">
						<?php foreach ( array( 'ASC', 'DESC' ) as $value ) : ?>
							<option <?php selected( $value, 'ASC' ); ?>><?php echo $value; ?></option>
						<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Schaltet die Anzeige der aktuellen Beitragsanzahl je Kategorie ein oder aus.', 'mp' ); ?></span></span> show_count</th>
				<td>
					<input type="checkbox" name="show_count" data-default="" value="1" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Legt die Anzahl der anzuzeigenden Kategorien fest. Dadurch wird der SQL-LIMIT-Wert gesetzt.', 'mp' ); ?></span></span> number</th>
				<td>
					<input type="text" name="limit" data-default="" value="" />
				</td>
			</tr>
		</table>
		<?php
	}
	
	/**
	 * Displays the [mp_global_categories_list] short code attributes
	 *
	 * @since 1.0
	 * @access public
	 */
	public function display_mp_global_tag_cloud_attributes() {
		?>
		<table id="mp-global-tag-cloud-shortcode" class="form-table" style="display:none">
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Sortierung der Tags.', 'mp' ); ?></span></span> orderby</th>
				<td>
					<label for="mp-tag-cloud-orderby-name"><input type="radio" name="orderby" id="mp-tag-cloud-orderby-name" data-default="name" value="name" checked /> <?php _e( 'Name', 'mp' ); ?></label><br />
					<label for="mp-tag-cloud-orderby-count"><input type="radio" name="orderby" id="mp-tag-cloud-orderby-count" data-default="count" value="count" /> <?php _e( 'Anzahl', 'mp' ); ?></label>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Sortierreihenfolge.', 'mp' ); ?></span></span> order</th>
				<td>
					<label for="mp-tag-cloud-order-asc"><input type="radio" name="order" id="mp-tag-cloud-order-asc" data-default="ASC" value="ASC" checked /> <?php _e( 'Aufsteigend', 'mp' ); ?></label><br />
					<label for="mp-tag-cloud-order-desc"><input type="radio" name="order" id="mp-tag-cloud-order-desc" data-default="ASC" value="DESC" /> <?php _e( 'Absteigend', 'mp' ); ?></label><br />
					<label for="mp-tag-cloud-order-rand"><input type="radio" name="order" id="mp-tag-cloud-order-rand" data-default="RAND" value="RAND" /> <?php _e( 'Zufaellig', 'mp' ); ?></label>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Legt die Anzahl der anzuzeigenden Tags fest. Dadurch wird der SQL-LIMIT-Wert gesetzt.', 'mp' ); ?></span></span> number</th>
				<td>
					<input type="text" name="limit" data-default="" value="" />
				</td>
			</tr>
		</table>
		<?php
	}

	/**
	 * Displays the short code builder submit/reset buttons
	 *
	 * @since 1.0
	 * @access public
	 */
	public function display_shortcode_builder_form_buttons() {
		?>
		<p class="submit">
			<input class="button-primary" type="submit" value="<?php _e( 'Shortcode einfuegen', 'mp' ); ?>" />
			<!--<input class="button" type="button" value="<?php _e( 'Auf Standardwerte zuruecksetzen', 'mp' ); ?>" />-->
		</p>
		<?php
	}

	/**
	 * Enqueues admin javascript/css
	 *
	 * @since 1.0
	 * @access public
	 */
	public function enqueue_styles_scripts() {
		if ( isset( $_GET['page'] ) ) {
			$page = isset( $_GET['page'] );
		} else {
			$page = '';
		}
		
		$screenpage = get_current_screen();
		
		// We have to refactor this to accept all post types

		if ( $page == 'store-settings' 
			|| $page == 'store-settings-presentation' 
			|| $page == 'store-settings-notifications' 
			|| $page == 'store-settings-shipping' 
			|| $page == 'store-settings-payments' 
			|| $page == 'store-settings-productattributes' 
			|| $page == 'store-settings-capabilities'
			|| $page == 'store-settings-addons'
			|| ( isset( $_GET['taxonomy'] ) && ($_GET['taxonomy'] == 'product_category' || $_GET['taxonomy'] == 'product_tag') )
			|| ( isset( $_GET['post_type'] ) && ($_GET['post_type'] == 'mp_coupon' || $_GET['post_type'] == 'mp_order' || $_GET['post_type'] == 'product' || $_GET['post_type'] == 'page') ) 
			|| ( isset( $screenpage->post_type ) && ( $screenpage->post_type == "product" || $screenpage->post_type == "incsub_event" || $screenpage->post_type == "post" || $screenpage->post_type == "mp_order" || $screenpage->post_type == "mp_coupon" || $screenpage->post_type == "page") ) )  {

			   wp_enqueue_script( 'mp-shortcode-builder', mp_plugin_url( 'includes/admin/ui/js/shortcode-builder.js' ), array(), MP_VERSION );
		wp_localize_script( 'mp-shortcode-builder', 'MP_ShortCode_Builder', array(
			'select_product' => __( 'Produkt auswaehlen', 'mp' ),
		) );		}
	}

	/**
	 * Displays the short code builder button above the tinymce editor.
	 *
	 * @since 1.0
	 * @access public
	 */
	public function media_buttons( $editor_id ) {
		// I was trying to get the editor_id here, but it seems the editor is unique, uniqid() is used.
		
		$SC_Builder = true;
		if( isset( $_REQUEST['page'] ) && $_REQUEST['page'] == 'store-settings-addons' ) {
			$SC_Builder = false;
		}
		if( $SC_Builder ) {
		?>
		<a href="javascript:;" class="button mp-shortcode-builder-button" title="<?php _e( 'E-Commerce-Shortcode hinzufuegen', 'mp' ); ?>"><span class="wp-media-buttons-icon dashicons dashicons-cart"></span> <?php _e( 'E-Commerce-Shortcode hinzufuegen', 'mp' ); ?></a>
		<?php
		}
	}

}

MP_Shortcode_Builder::get_instance();
